app:
    resource: "@AppBundle/Controller/"
    type:     annotation

myapp_admincp:
    resource: "@AdminCPBundle/Controller/"
    type:     annotation
    prefix:   /admind

myapp:
    resource: "@NewsBundle/Controller/"
    type:     annotation
    prefix:   /abc