myapp_admincp:
    resource: "@AdminCPBundle/Controller/"
    type:     annotation
    prefix:   /

myapp_news:
    resource: "@NewsBundle/Controller/"
    type:     annotation
    prefix:   /

myapp_categories_news:
    resource: "@CategoriesNewsBundle/Controller/"
    type:     annotation
    prefix:   /