# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
   app.admincp_service:
     class: MyApp\AdminCP\Service\AdminCPService
     arguments: ["@doctrine.orm.entity_manager"]
     calls:
            - [ setContainer, [ '@service_container' ]]
   app.twig_extension:
           class: MyApp\Twig\AppExtension
           public: false
           tags:
               - { name: twig.extension }

