<?php

namespace MyApp\AdminCP\Repository\AdminCp;

use Doctrine\ORM\EntityRepository;

/**
 * IndexRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IndexRepository extends EntityRepository
{
}
